[features]
seeds = false
[programs.localnet]
swap_token_solana = "Cqvte55GwzjWgRiwjvNVRD5kPBUpkV3YFuGwQmPAcd6z"
[programs.devnet]
swap_token_solana = "14XAbvD2vPJBFa1yMztS4SrVe1LKDKKpQ5X5KvSAbdtG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/vietle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
